return {
  Ralts = true,
  Swablu = true,
  Bagon = true,
  Turtwig = true,
  Chimchar = true,
  Piplup = true,
  Audino = true,
  Hisuian_Zorua = true,
  Clauncher = false,
  Dedenne = true,
  Carbink = true,
  Goomy = true,
  Oranguru = true,
  Passimian = true,
  Turtonator = true,
  Skwovet = true,
  Galarian_Meowth = true,
  Terapagos = true,
  Hisuian_Sneasel = true,
  customStakes = true,
  orderJokers = true,
  pokemon_only = false,
  gallery_width = 5,
  -- customItems = true,
}