return {
  ralts = true,
  swablu = true,
  bagon = true,
  turtwig = true,
  chimchar = true,
  piplup = true,
  audino = true,
  hisuian_zorua = true,
  clauncher = true,
  dedenne = true,
  carbink = true,
  goomy = true,
  oranguru = true,
  passimian = true,
  turtonator = true,
  skwovet = true,
  galarian_meowth = true,
  terapagos = true,
  hisuian_sneasel = true,
  customStakes = true,
  orderJokers = true,
  pokemon_only = false,
  gallery_width = 5,
  -- customItems = true,
}