return {
  ralts = true,
  swablu = true,
  bagon = false,
  turtwig = true,
  chimchar = true,
  piplup = true,
  snover = true,
  victini = true,
  audino = true,
  hisuian_zorua = true,
  clauncher = true,
  dedenne = true,
  carbink = true,
  goomy = true,
  oranguru = true,
  passimian = true,
  turtonator = true,
  skwovet = true,
  applin = true,
  galarian_meowth = true,
  frigibax = true,
  terapagos = true,
  hisuian_sneasel = (SMODS.Mods["ToxicStall"] or {}).can_load and true or false,
  customStakes = true,
  gallery_width = 5,
  -- customItems = true,
}