[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# Remoraid + Octillery Retrigger fix
[[patches]]
[patches.pattern]
target = '=[SMODS Pokermon "pokemon/pokejokers_08.lua"]'
pattern = '''
if not context.blueprint then
        card.ability.extra.cards = card.ability.extra.cards + 1
      end
'''
position = "at"
payload = '''
if not context.blueprint and not context.retrigger_joker then
        card.ability.extra.cards = card.ability.extra.cards + 1
      end
'''
match_indent = true