[manifest]
version = "1.0.0"
dump_lua = true
priority = 21

### Audino Post-Evolution context
[[patches]]
[patches.pattern]
target = '=[SMODS Pokermon "functions/pokefunctions.lua"]'
pattern = '''
card:set_ability(new_card, true)
card:set_cost()
'''
position = "after"
payload = '''

if G.P_CENTERS[to_key].rarity ~= "poke_mega" and G.P_CENTERS[old_key].rarity ~= "poke_mega" then SMODS.calculate_context({poke_evolved = true}) end
'''
match_indent = true