[manifest]
version = "1.0.0"
dump_lua = true
priority = 1

# Elite Stake Showdown Call
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = '''
elseif not v.boss.showdown and (v.boss.min <= math.max(1, G.GAME.round_resets.ante) and ((math.max(1, G.GAME.round_resets.ante))%G.GAME.win_ante ~= 0 or G.GAME.round_resets.ante < 2)) then
    eligible_bosses[k] = res and true or nil
'''
position = "before"
payload = '''
elseif G.GAME.modifiers.poke_elite4 then
    if v.boss.showdown and G.GAME.round_resets.ante >= 2 and
            (G.GAME.round_resets.ante % G.GAME.win_ante >= G.GAME.win_ante - 3 or G.GAME.round_resets.ante % G.GAME.win_ante == 0) then
        eligible_bosses[k] = res and true
    elseif not v.boss.showdown and v.boss.min <= math.max(1, G.GAME.round_resets.ante) and
            (math.max(1, G.GAME.round_resets.ante) % G.GAME.win_ante ~= 0 and not
            (math.max(1, G.GAME.round_resets.ante) % G.GAME.win_ante >= G.GAME.win_ante - 3) or G.GAME.round_resets.ante < 2) then
        eligible_bosses[k] = res and true
    end
'''
match_indent = true