[manifest]
version = "1.0.0"
dump_lua = true
priority = 21

# Gallade Planet Insert
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = '''
function level_up_hand(card, hand, instant, amount)
'''
position = "after"
payload = '''
    if next(SMODS.find_card('j_nacho_gallade')) and card.ability and card.ability.set == 'Planet' then
        return true
    end
'''
match_indent = true


# Mega Gallade Hand Debuff Logic
[[patches]]
[patches.pattern]
target = "blind.lua"
pattern = '''
if self.disabled then return end
    local obj = self.config.blind
    if obj.debuff_hand and type(obj.debuff_hand) == 'function' then
'''
position = "before"
payload = '''
    if next(SMODS.find_card('j_nacho_mega_gallade')) then return end
'''
match_indent = true


# Turtonator Cerulean Bell compat.
[[patches]]
[patches.pattern]
target = "blind.lua"
pattern = '''
forced_card.ability.forced_selection = true
'''
position = "after"
payload = '''
forced_card.ability.pokermon_forced_selection = true
'''
match_indent = true


# Passimian Evo Logic
[[patches]]
[patches.pattern]
target = '=[SMODS Pokermon "functions/pokefunctions.lua"]'
pattern = '''
if immediate then
    poke_backend_evolve(card, to_key)
  else
'''
position = "before"
payload = '''
if card.config.center.key == 'j_nacho_passimian' then
    immediate = true
end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = '=[SMODS Pokermon "functions/pokefunctions.lua"]'
pattern = '''local custom_values_to_keep = {}'''
position = "before"
payload = '''
-- Passimian passed abilities don't "Evolve" per se
if card.config.center.key == 'j_nacho_passimian' then
  card.ability.extra.to_key = to_key
  card.config.center:receive_card(card)
  return
end

'''
match_indent = true

[[patches]]
[patches.pattern]
target = '=[SMODS Pokermon "functions/energyfunctions.lua"]'
pattern = '''card.ability.extra[name] =  data + (card.config.center.config.extra[name] * addition) * (card.ability.extra.escale or 1)'''
position = "at"
payload = '''
if card.config.center.key == 'j_nacho_passimian' then
  card.ability.extra[name] =  data + (card.ability.received_card.config.extra[name] * addition) * (card.ability.extra.escale or 1)
else
  card.ability.extra[name] =  data + (card.config.center.config.extra[name] * addition) * (card.ability.extra.escale or 1)
end
'''
match_indent = true


# Ensuring that Terapagos-Stellar makes Pokemon always Tera Stellar
[[patches]]
[patches.pattern]
target = '=[SMODS Pokermon "functions/pokefunctions.lua"]'
pattern = '''
if sticker_type then
    apply_type = sticker_type
'''
position = "before"
payload = '''
if next(SMODS.find_card('j_nacho_terapagos_stellar')) then
    sticker_type = "Stellar"
end
'''
match_indent = true