[manifest]
version = "1.0.0"
dump_lua = true
priority = 22

# Gallade Planet Insert
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = '''
function level_up_hand(card, hand, instant, amount)
'''
position = "after"
payload = '''
    if next(SMODS.find_card('j_nacho_gallade')) and card.ability and card.ability.set == 'Planet' then
        return true
    end
'''
match_indent = true


# Mega Gallade Hand Debuff Logic

[[patches]]
[patches.pattern]
target = "blind.lua"
pattern = '''
if self.disabled then return end
    local obj = self.config.blind
    if obj.debuff_hand and type(obj.debuff_hand) == 'function' then
'''
position = "before"
payload = '''
    if next(SMODS.find_card('j_nacho_mega_gallade')) then return end
'''
match_indent = true


# Ensuring that Terapagos-Stellar makes Pokemon always Tera Stellar
[[patches]]
[patches.pattern]
target = '=[SMODS Pokermon "functions/pokefunctions.lua"]'
pattern = '''
if sticker_type then
    apply_type = sticker_type
'''
position = "before"
payload = '''
if next(SMODS.find_card('j_nacho_terapagos_stellar')) then
    sticker_type = "Stellar"
end
'''
match_indent = true











