[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# Remoraid + Octillery Retrigger Fix
[[patches]]
[patches.pattern]
target = '=[SMODS Pokermon "pokemon/pokejokers_08.lua"]'
pattern = '''
if not context.blueprint then
        card.ability.extra.cards = card.ability.extra.cards + 1
      end
'''
position = "at"
payload = '''
if not context.blueprint and not context.retrigger_joker then
        card.ability.extra.cards = card.ability.extra.cards + 1
      end
'''
match_indent = true



# Ralts-line Cross-Compatibility with Pokermon-Maelmc

# Family table update
[[patches]]
[patches.pattern]
target = '=[SMODS Pokermon-Maelmc "pokermon-maelmc.lua"]'
pattern = '''
table.insert(pokermon.family,{"ralts","kirlia","gardevoir","mega_gardevoir"})
'''
position = "at"
payload = '''
'''
match_indent = true

# List update
[[patches]]
[patches.pattern]
target = '=[SMODS Pokermon-Maelmc "pokemon/pokemon-maelmc_03.lua"]'
pattern = '''
    ralts, kirlia, gardevoir, mega_gardevoir,
    kecleon,
    lunatone, solrock,
'''
position = "at"
payload = '''
    kecleon,
    lunatone, solrock,
'''
match_indent = true

# Challenge update
[[patches]]
[patches.pattern]
target = '=[SMODS Pokermon-Maelmc "challenges/maelmcchallenges.lua"]'
pattern = '''
{id = "j_maelmc_ralts"},
'''
position = "at"
payload = '''
{id = "j_nacho_ralts"},
'''
match_indent = true





