[manifest]
version = "1.0.0"
dump_lua = true
priority = 1

# Remoraid + Octillery Retrigger Fix
[[patches]]
[patches.pattern]
target = '=[SMODS Pokermon "pokemon/pokejokers_08.lua"]'
pattern = '''
if not context.blueprint then
        card.ability.extra.cards = card.ability.extra.cards + 1
      end
'''
position = "at"
payload = '''
if not context.blueprint and not context.retrigger_joker then
        card.ability.extra.cards = card.ability.extra.cards + 1
      end
'''
match_indent = true



# Ralts-line Cross-Compatibility with Pokermon-Maelmc

# Challenge update
[[patches]]
[patches.pattern]
target = '=[SMODS Pokermon-Maelmc "challenges/maelmcchallenges.lua"]'
pattern = '''
{id = "j_maelmc_ralts"},
'''
position = "at"
payload = '''
{id = "j_nacho_ralts"},
'''
match_indent = true





