[manifest]
version = "1.0.0"
dump_lua = true
priority = 1


### Passimian : Copy Card fix
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = '''
for k, v in pairs(other.ability) do
    if type(v) == 'table' then 
        new_card.ability[k] = copy_table(v)
    else
        new_card.ability[k] = v
    end
end
'''
position = "at"
match_indent = true
payload = '''
if other.config.center.name == "passimian" then
  if other.ability.received_card then
    new_card:set_ability(other.config.center)
    new_card.config.center:receive_card(new_card, other.ability.received_card.key)
  end
else
  for k, v in pairs(other.ability) do
      if type(v) == 'table' then 
          new_card.ability[k] = copy_table(v)
      else
          new_card.ability[k] = v
      end
  end
end
'''