[manifest]
version = "1.0.0"
dump_lua = true
priority = -1


# Elite Stake Showdown Call
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = '''
elseif v.boss.showdown and (G.GAME.round_resets.ante)%G.GAME.win_ante == 0 and G.GAME.round_resets.ante >= 2 then
'''
position = "before"
payload = '''
elseif G.GAME.modifiers.elite4 and v.boss.showdown and 
            (((G.GAME.round_resets.ante)%G.GAME.win_ante == G.GAME.win_ante - 3 and G.GAME.round_resets.ante >= 2) or
            ((G.GAME.round_resets.ante)%G.GAME.win_ante == G.GAME.win_ante - 2 and G.GAME.round_resets.ante >= 2) or
            ((G.GAME.round_resets.ante)%G.GAME.win_ante == G.GAME.win_ante - 1 and G.GAME.round_resets.ante >= 2) or 
            ((G.GAME.round_resets.ante)%G.GAME.win_ante == 0 and G.GAME.round_resets.ante >= 2)) then
    eligible_bosses[k] = true
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = '''
elseif not v.boss.showdown and (v.boss.min <= math.max(1, G.GAME.round_resets.ante) and ((math.max(1, G.GAME.round_resets.ante))%G.GAME.win_ante ~= 0 or G.GAME.round_resets.ante < 2)) then
            eligible_bosses[k] = true
'''
position = "at"
payload = '''
elseif not v.boss.showdown and not G.GAME.modifiers.elite4 and (v.boss.min <= math.max(1, G.GAME.round_resets.ante) and ((math.max(1, G.GAME.round_resets.ante))%G.GAME.win_ante ~= 0 or G.GAME.round_resets.ante < 2)) then
            eligible_bosses[k] = true
elseif not v.boss.showdown and G.GAME.modifiers.elite4 and (v.boss.min <= math.max(1, G.GAME.round_resets.ante) and 
((math.max(1, G.GAME.round_resets.ante))%G.GAME.win_ante ~= 0 and (math.max(1, G.GAME.round_resets.ante))%G.GAME.win_ante ~= G.GAME.win_ante - 1 
and (math.max(1, G.GAME.round_resets.ante))%G.GAME.win_ante ~= G.GAME.win_ante - 2 and (math.max(1, G.GAME.round_resets.ante))%G.GAME.win_ante ~= G.GAME.win_ante - 3 or G.GAME.round_resets.ante < 2)) then
            eligible_bosses[k] = true
'''
match_indent = true


# Pokermon Family Stake Sticker Logic
[[patches]]
[patches.pattern]
target = "functions/misc_functions.lua"
pattern = '''
if G.PROFILES[G.SETTINGS.profile].joker_usage[v.config.center_key] then
        G.PROFILES[G.SETTINGS.profile].joker_usage[v.config.center_key].wins = G.PROFILES[G.SETTINGS.profile].joker_usage[v.config.center_key].wins or {}
        G.PROFILES[G.SETTINGS.profile].joker_usage[v.config.center_key].wins[G.GAME.stake] = (G.PROFILES[G.SETTINGS.profile].joker_usage[v.config.center_key].wins[G.GAME.stake] or 0) + 1
        G.PROFILES[G.SETTINGS.profile].joker_usage[v.config.center_key].wins_by_key[SMODS.stake_from_index(G.GAME.stake)] = (G.PROFILES[G.SETTINGS.profile].joker_usage[v.config.center_key].wins_by_key[SMODS.stake_from_index(G.GAME.stake)] or 0) + 1
      end
'''
position = "after"
payload = '''set_joker_family_win(v)'''
match_indent = true